import os

DATA_FOLDER = "data/samples"
GOLDEN_FOLDER = os.path.join(DATA_FOLDER, "golden")
BOUNDING_BOX_INCREASE_FACTOR = 0.5
BOUNDING_BOX_MIN_SIZE = 224
IOU_FILTER_THRESHOLD = 0.5
GAUSSIAN_BLUR_ON_MERGE = False
CONDENSE_SEGMENTATION_MASKS = True